# Generated by Django 4.0.6 on 2022-07-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLiked', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('genre', models.CharField(default='Action', max_length=10)),
            ],
        ),
    ]
